# Generated by Django 4.1.4 on 2023-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_detection', '0002_alter_recipe_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(upload_to='food_detection/static/recipe_picture'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(max_length=20),
        ),
    ]
